import { useState } from "react";
import "./_group.css";

const PROJECTS = [
  ["Outback Concrete Coatings", "Industry-leading. New standard.", "The Outback site is what a coatings website looks like when it stops acting like a brochure. An industry-leading build that sets the new standard for the category and works as hard as the crews do.", "outback-pool.jpg"],
  ["Brand Identity: St. Thomas Football", "The 2026 slate, unveiled.", "Twelve opponents, twelve helmets, one statement. The official 2026 schedule reveal for St. Thomas Football, built to be shared, saved, and screenshotted.", "ust-tommie.png"],
];

export function Homepage({ option }: { option: "editorial" | "grotesk" | "humanist" }) {
  const [menu, setMenu] = useState(false);
  const specimen = {
    editorial: { name: "Editorial Tension", fonts: "Fraunces + Instrument Sans" },
    grotesk: { name: "Punchy Grotesk", fonts: "Archivo Black + Archivo" },
    humanist: { name: "Warm Humanist", fonts: "Sora + DM Sans" },
  }[option];
  return <main className={`sddfo sddfo--${option}`}>
    <aside className="sddfo__spine"><a href="#top" className="sddfo__logo"><img src="/__mockup/images/sdd-font-options/logo-white.svg" alt="Stuffed Dog Digital" /></a><nav className="sddfo__nav"><a href="#work"><i />Work</a><a href="#about"><i />About</a><a href="#approach"><i />How We Get Results</a><a href="#contact"><i />Contact</a></nav><div className="sddfo__spine-bottom"><a className="sddfo__start" href="#contact">Start Something</a><p className="sddfo__motto">Vive La Humanity.</p></div></aside>
    <header className="sddfo__mobile"><img src="/__mockup/images/sdd-font-options/logo-white.svg" alt="Stuffed Dog Digital" /><button onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? "×" : "≡"}</button>{menu && <nav><a onClick={() => setMenu(false)} href="#work">Work</a><a onClick={() => setMenu(false)} href="#about">About</a><a onClick={() => setMenu(false)} href="#approach">How We Get Results</a><a onClick={() => setMenu(false)} href="#contact">Contact</a></nav>}</header>
    <div className="sddfo__content">
      <section id="top" className="sddfo__hero"><div className="sddfo__specimen"><span>{specimen.name}</span><strong>Aa Rr 0123</strong><small>{specimen.fonts}</small></div><div className="sddfo__hero-copy"><p className="sddfo__eyebrow">Stuffed Dog Digital · Creative Human Intelligence</p><h1>Intelligence can be artificial.<br />Imagination cannot.</h1><p className="sddfo__lede">AI can draft a thousand campaigns before breakfast. Not one of them will care whether you win. We blend technology into human craft, and make work people actually feel.</p><p className="sddfo__hero-motto">Vive La Humanity.</p></div><span className="sddfo__scroll"><i />Scroll</span></section>
      <section className="sddfo__story"><div className="sddfo__wrap"><p className="sddfo__label">The moment we're in</p><p className="sddfo__story-copy"><span className="sddfo__dim">Machines can make marketing now. Infinite. Instant. Optimized. </span>And all of it sounds the same. When anyone can generate everything, the only work that cuts through is the work that feels <span className="sddfo__blue">alive.</span> That has always been, and will always be, a <span className="sddfo__blue">human</span> job.</p></div></section>
      <section id="work" className="sddfo__work"><div className="sddfo__wrap"><div className="sddfo__work-head"><p className="sddfo__label sddfo__green">Highlighted Projects</p><h2>Some work you should<br />see up close.</h2><p className="sddfo__copy">Films, sites, systems, and campaigns. A closer look at pieces we're proud of and clients are winning with.</p></div>{PROJECTS.map(([eyebrow,title,copy,image], index) => <article key={title} className={`sddfo__project ${index ? "sddfo__project--flip" : ""}`}><div className="sddfo__media"><img src={`/__mockup/images/sdd-font-options/${image}`} alt="" /></div><div><p className="sddfo__eyebrow">{eyebrow}</p><h3>{title}</h3><p>{copy}</p><a className="sddfo__link" href="#contact">View Case Study</a></div></article>)}</div></section>
      <section id="approach" className="sddfo__value"><div className="sddfo__wrap"><p className="sddfo__label">The Commercial Value</p><h2>Art that sells.<br /><span className="sddfo__muted">Systems that scale.</span></h2><p className="sddfo__copy">Beautiful design is the baseline. We build creative that commands attention and infrastructure that converts it into revenue. No fluff, just measurable outcomes.</p><div className="sddfo__steps">{[["01","Find The Friction","Before we make a single creative decision, we analyze your market gaps, audience behaviors, and sales barriers."],["02","Engineer The Asset","Websites and films aren't art projects—they're revenue engines, optimized for speed, clarity, and lead generation."],["03","Command Attention","We deploy targeted distribution, SEO, and paid media to attract qualified traffic and make every acquisition dollar work harder."],["04","Compound The Value","We measure what matters, learn from real behavior, and keep optimizing—so the work continues earning after launch."]].map(([n,t,b])=><div className="sddfo__step" key={n}><span className="sddfo__number">{n}</span><h3>{t}</h3><p>{b}</p></div>)}</div></div></section>
      <section id="about" className="sddfo__manifesto"><div className="sddfo__wrap"><p className="sddfo__label">What we believe</p><p className="sddfo__manifesto-copy">We aspire to create work that outlives the campaign. Work that inspires pride, strengthens communities and helps good organizations leave their mark on the people they serve.</p><p className="sddfo__manifesto-copy sddfo__manifesto-copy--muted">Relationships over transactions. Character over recognition. Purpose over profit.</p><p className="sddfo__manifesto-copy">We don't want to be the biggest agency in the world. We want to be the one you trust <span className="sddfo__blue">when the story matters most.</span></p><div className="sddfo__quote">"We elevate work, drive revenue, sell ideas, and build trust. Our goal is to make everything around us better, and our superpower is our empathy."<p className="sddfo__byline">Blake Allen</p></div><p className="sddfo__big-motto">Vive La Humanity.</p></div></section>
      <section id="contact" className="sddfo__cta"><h2>Got something worth fighting for?</h2><p>Bring us the story a machine couldn't tell. We'll make people feel it.</p><div className="sddfo__buttons"><a href="mailto:hello@stuffeddogdigital.com" className="sddfo__button">Make Your Mark</a><a href="#work" className="sddfo__button sddfo__button--outline">See the Work</a></div></section>
    </div>
  </main>;
}