// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sdd-animated-spine/AnimatedSpine.tsx": () => import("../components/mockups/sdd-animated-spine/AnimatedSpine.tsx"),
  "./components/mockups/sdd-growth-diagnostic/GrowthDiagnostic.tsx": () => import("../components/mockups/sdd-growth-diagnostic/GrowthDiagnostic.tsx"),
  "./components/mockups/sdd-font-options/FontEditorial.tsx": () => import("../components/mockups/sdd-font-options/FontEditorial.tsx"),
  "./components/mockups/sdd-font-options/FontGrotesk.tsx": () => import("../components/mockups/sdd-font-options/FontGrotesk.tsx"),
  "./components/mockups/sdd-font-options/FontHumanist.tsx": () => import("../components/mockups/sdd-font-options/FontHumanist.tsx"),
  "./components/mockups/sdd-project-channel/ProjectChannel.tsx": () => import("../components/mockups/sdd-project-channel/ProjectChannel.tsx"),
  "./components/mockups/sdd-vibe/WarmCraft.tsx": () => import("../components/mockups/sdd-vibe/WarmCraft.tsx")
};
